plugins:
  - jekyll-gist
  - jekyll-seo-tag

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

ga_id: "UA-134504184-1"

title: "Alasco | Tech Blog"
tagline: "Alasco Tech Blog - Where the Product & Engineering team of Alasco shares their stories"
description: "Stories and learnings from our journey on building the SaaS project controlling tool Alasco. We value positivity, appreciation, ambition and trust! We are driven by the idea to make higher quality and affordable housing available to society."
twitter:
  username: tech_alasco
  card: summary
logo: assets/images/webclip.png
social:
  name: Alasco GmbH
  links:
    - https://twitter.com/tech_alasco
    - https://www.facebook.com/alasco.software
    - https://www.linkedin.com/company/alasco-software/
    - https://github.com/alasco-tech/
